; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200


build_flags =
  -D ESP32_AUDIO_OUT_MODE=1   ; 1 = INTERNAL_DAC → GPIO25 (L) + GPIO26 (R)

lib_deps =
  fastled/FastLED @ ^3.6.0
  sensorium/Mozzi @ ~1.1.1
